[project]
name = "pete_e"
version = "1.0.0"
description = "Personal health and fitness orchestrator."

# These are the essential packages needed to RUN the application
dependencies = [
    "psycopg[binary,pool]==3.1.18",
    "pydantic==2.6.4",
    "pydantic-settings==2.2.1",
    "requests==2.31.0",
    "fastapi==0.110.0",
    "uvicorn[standard]==0.27.1",
    "typer[all]==0.12.1",
    "Jinja2==3.1.3",
    "python-dateutil==2.8.2",
    "tenacity==9.1.2",
]

[project.optional-dependencies]
# These are packages for development, testing, and publishing.
# Install with: pip install .[dev]
dev = [
    "pytest==8.1.1",
    "rich==13.7.0",
    "twine==4.0.2",
    "ruff==0.3.7",
]

[project.scripts]
pete-e = "pete_e.cli.messenger:app"

[tool.setuptools.packages.find]
where = ["."]
