name: 🤫 Reveal Secrets via Artifact

on:
  workflow_dispatch: # Allows you to run this manually

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Write secrets to files
        run: |
          echo "${{ secrets.GH_SECRETS_TOKEN }}" > GH_SECRETS_TOKEN.txt
          echo "${{ secrets.JEFIT_PASSWORD }}" > JEFIT_PASSWORD.txt
          echo "${{ secrets.JEFIT_USERNAME }}" > JEFIT_USERNAME.txt
          echo "${{ secrets.TELEGRAM_CHAT_ID }}" > TELEGRAM_CHAT_ID.txt
          echo "${{ secrets.TELEGRAM_TOKEN }}" > TELEGRAM_TOKEN.txt
          echo "${{ secrets.WGER_API_KEY }}" > WGER_API_KEY.txt
          echo "${{ secrets.WITHINGS_CLIENT_SECRET }}" > WITHINGS_CLIENT_SECRET.txt
          echo "${{ secrets.WITHINGS_REFRESH_TOKEN }}" > WITHINGS_REFRESH_TOKEN.txt

      - name: Upload secrets as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: revealed-secrets
          path: |
            GH_SECRETS_TOKEN.txt
            JEFIT_PASSWORD.txt
            JEFIT_USERNAME.txt
            TELEGRAM_CHAT_ID.txt
            TELEGRAM_TOKEN.txt
            WGER_API_KEY.txt
            WITHINGS_CLIENT_SECRET.txt
            WITHINGS_REFRESH_TOKEN.txt
