name: 🤫 Reveal Secrets

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal GH_SECRETS_TOKEN
        run: echo "GH_SECRETS_TOKEN_B64=$(echo -n ${{ secrets.GH_SECRETS_TOKEN }} | base64)"

      - name: Reveal JEFIT_PASSWORD
        run: echo "JEFIT_PASSWORD_B64=$(echo -n ${{ secrets.JEFIT_PASSWORD }} | base64)"

      - name: Reveal JEFIT_USERNAME
        run: echo "JEFIT_USERNAME_B64=$(echo -n ${{ secrets.JEFIT_USERNAME }} | base64)"

      - name: Reveal TELEGRAM_CHAT_ID
        run: echo "TELEGRAM_CHAT_ID_B64=$(echo -n ${{ secrets.TELEGRAM_CHAT_ID }} | base64)"

      - name: Reveal TELEGRAM_TOKEN
        run: echo "TELEGRAM_TOKEN_B64=$(echo -n ${{ secrets.TELEGRAM_TOKEN }} | base64)"

      - name: Reveal WGER_API_KEY
        run: echo "WGER_API_KEY_B64=$(echo -n ${{ secrets.WGER_API_KEY }} | base64)"

      - name: Reveal WITHINGS_CLIENT_SECRET
        run: echo "WITHINGS_CLIENT_SECRET_B64=$(echo -n ${{ secrets.WITHINGS_CLIENT_SECRET }} | base64)"

      - name: Reveal WITHINGS_REFRESH_TOKEN
        run: echo "WITHINGS_REFRESH_TOKEN_B64=$(echo -n ${{ secrets.WITHINGS_REFRESH_TOKEN }} | base64)"
