name: Apply plan to Wger (auto on push)

on:
  push:
    branches: [ "main" ]  # change if your default branch differs
    paths:
      - "integrations/wger/plans/*.json"

permissions:
  contents: write

concurrency:
  group: wger-apply
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Find changed plan files
        id: files
        run: |
          set -e
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^integrations/wger/plans/.*\.json$' || true)
          if [ -z "$CHANGED" ]; then
            CHANGED=$(git show --name-only --pretty="" ${{ github.sha }} | grep -E '^integrations/wger/plans/.*\.json$' || true)
          fi
          echo "changed<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Changed files:"
          echo "$CHANGED"

      - name: Apply each plan
        if: ${{ steps.files.outputs.changed != '' }}
        env:
          WGER_API_KEY: ${{ secrets.WGER_API_KEY }}
          WGER_BASE_URL: ${{ vars.WGER_BASE_URL || 'https://wger.de/api/v2' }}
        run: |
          set -e
          for f in ${{ steps.files.outputs.changed }}; do
            echo "::group::Applying $f"
            python integrations/wger/routine_builder.py --plan "$f" --replace-days
            echo "::endgroup::"
          done

      - name: Commit routine state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add integrations/wger/state/
          if git diff --cached --quiet; then
            echo "No state changes."
          else
            git commit -m "chore(wger): update routine state (auto-apply)"
            git push
          fi
