name: Apply WGER Routine Plan

on:
  workflow_dispatch:
    inputs:
      plan_path:
        description: "Path to plan JSON (e.g., integrations/wger/plans/plan_2025-09-01_2025-09-28.json)"
        required: true
  push:
    paths:
      - "integrations/wger/plans/*.json"
      - "integrations/wger/routine_builder.py"

permissions:
  contents: read

concurrency:
  group: wger-apply
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Show plan target
        run: |
          set -e
          if [ -n "${{ github.event.inputs.plan_path }}" ]; then
            PLAN="${{ github.event.inputs.plan_path }}"
          else
            # recent change: pick the last modified plan
            PLAN="$(ls -1t integrations/wger/plans/*.json | head -n 1 || true)"
          fi
          echo "PLAN=${PLAN}" >> $GITHUB_ENV
          echo "Applying ${PLAN}"
          test -f "$PLAN"

      - name: Apply plan to WGER
        env:
          WGER_API_KEY: ${{ secrets.WGER_API_KEY }}
          WGER_BASE_URL: ${{ secrets.WGER_BASE_URL }}
        run: |
          set -e
          python integrations/wger/routine_builder.py "$PLAN"