name: Pull yesterday's Wger logs

on:
  schedule:
    - cron: "15 2 * * *"   # 02:15 UTC daily (≈03:15 UK summer)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  pull-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil
      - name: Fetch logs
        env:
          WGER_API_KEY: ${{ secrets.WGER_API_KEY }}
          WGER_BASE_URL: ${{ vars.WGER_BASE_URL }}
        run: |
          python integrations/wger/pull_wger_logs.py
      - name: Commit logs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add integrations/wger/logs/
          if git diff --cached --quiet; then
            echo "No new logs."
          else
            git commit -m "chore(wger): refresh logs"
            git push
          fi
