name: Sync Wger

on:
  schedule:
    - cron: "0 2 * * *"   # 03:00 UK in summer
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wger-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Sync WGER Logs (past 7 days)
        run: python integrations/wger/sync_wger_logs.py
        env:
          WGER_API_KEY: ${{ secrets.WGER_API_KEY }}
          PYTHONPATH: .

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/wger/days
          git commit -m "WGER logs sync (past 7 days)" || echo "No changes"
          git push