name: Upload workouts to Wger

on:
  workflow_dispatch:
    inputs:
      schedule_json:
        description: "Path to the schedule JSON (e.g., integrations/wger/wger_workouts_sep2025.json)"
        required: true
        default: "integrations/wger/wger_workouts_sep2025.json"
      dry_run:
        description: "If true, just print what would be uploaded"
        required: false
        default: "false"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Upload schedule to Wger
        env:
          WGER_API_KEY: ${{ secrets.WGER_API_KEY }}
          # Optional override (e.g., for self-host): set Actions Variable WGER_BASE_URL to "https://yourhost/api/v2"
          WGER_BASE_URL: ${{ vars.WGER_BASE_URL }}
        run: |
          set -e
          DRY_ARG=""
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            DRY_ARG="--dry-run"
          fi

          echo "[wger] Base URL: ${WGER_BASE_URL:-https://wger.de/api/v2}"
          echo "[wger] Dry run: $([ -n "$DRY_ARG" ] && echo YES || echo NO)"
          echo "[wger] Reading schedule: ${{ github.event.inputs.schedule_json }}"

          python integrations/wger/wger_uploads.py \
            "${{ github.event.inputs.schedule_json }}" \
            $DRY_ARG